/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import negocio.basica.Vendedor;

/**
 *
 * @author aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cadastros = new javax.swing.JMenu();
        menu_cadastroCliente = new javax.swing.JMenuItem();
        menu_cadastroFornecedor = new javax.swing.JMenuItem();
        menu_cadastroProduto = new javax.swing.JMenuItem();
        menu_cadastroVendedor = new javax.swing.JMenuItem();
        menu_vendas = new javax.swing.JMenu();
        menu_vendasEmitirPed = new javax.swing.JMenuItem();
        menu_Colsultar = new javax.swing.JMenu();
        menu_consultarCliente = new javax.swing.JMenuItem();
        menu_consultarFornecedor = new javax.swing.JMenuItem();
        menu_consultarProdutos = new javax.swing.JMenuItem();
        menu_consultarVendedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icones/Logo.jpg"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 547, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 216, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        menu_cadastros.setText("Cadastros");

        menu_cadastroCliente.setText("Cliente");
        menu_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastroClienteActionPerformed(evt);
            }
        });
        menu_cadastros.add(menu_cadastroCliente);

        menu_cadastroFornecedor.setText("Fornecedor");
        menu_cadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastroFornecedorActionPerformed(evt);
            }
        });
        menu_cadastros.add(menu_cadastroFornecedor);

        menu_cadastroProduto.setText("Produtos");
        menu_cadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastroProdutoActionPerformed(evt);
            }
        });
        menu_cadastros.add(menu_cadastroProduto);

        menu_cadastroVendedor.setText("Vendedor");
        menu_cadastroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastroVendedorActionPerformed(evt);
            }
        });
        menu_cadastros.add(menu_cadastroVendedor);

        jMenuBar1.add(menu_cadastros);

        menu_vendas.setText("Vendas");

        menu_vendasEmitirPed.setText("Emitir Pedido");
        menu_vendasEmitirPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_vendasEmitirPedActionPerformed(evt);
            }
        });
        menu_vendas.add(menu_vendasEmitirPed);

        jMenuBar1.add(menu_vendas);

        menu_Colsultar.setText("Consultar");

        menu_consultarCliente.setText("Cliente");
        menu_consultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consultarClienteActionPerformed(evt);
            }
        });
        menu_Colsultar.add(menu_consultarCliente);

        menu_consultarFornecedor.setText("Fornecedor");
        menu_consultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consultarFornecedorActionPerformed(evt);
            }
        });
        menu_Colsultar.add(menu_consultarFornecedor);

        menu_consultarProdutos.setText("Produtos");
        menu_consultarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consultarProdutosActionPerformed(evt);
            }
        });
        menu_Colsultar.add(menu_consultarProdutos);

        menu_consultarVendedor.setText("Vendedor");
        menu_consultarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consultarVendedorActionPerformed(evt);
            }
        });
        menu_Colsultar.add(menu_consultarVendedor);

        jMenuBar1.add(menu_Colsultar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_cadastroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastroVendedorActionPerformed
        // TODO add your handling code here:
        CadastroVendedor cv = new CadastroVendedor();
        cv.setVisible(true);
    }//GEN-LAST:event_menu_cadastroVendedorActionPerformed

    private void menu_consultarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consultarVendedorActionPerformed
        // TODO add your handling code here:
        ConsultaVendedor cv = new ConsultaVendedor();
        cv.setVisible(true);
    }//GEN-LAST:event_menu_consultarVendedorActionPerformed

    private void menu_consultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consultarClienteActionPerformed
        // TODO add your handling code here:
        ConsultaCliente csc = new ConsultaCliente();
        csc.setVisible(true);
    }//GEN-LAST:event_menu_consultarClienteActionPerformed

    private void menu_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastroClienteActionPerformed
        // TODO add your handling code here:
        CadastroCliente cc = new CadastroCliente();
        cc.setVisible(true);
    }//GEN-LAST:event_menu_cadastroClienteActionPerformed

    private void menu_cadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastroFornecedorActionPerformed
        // TODO add your handling code here:
        CadastroFornecedor cf = new CadastroFornecedor();
        cf.setVisible(true);
    }//GEN-LAST:event_menu_cadastroFornecedorActionPerformed

    private void menu_cadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastroProdutoActionPerformed
        // TODO add your handling code here:
        CadastroProduto cp = new CadastroProduto();
        cp.setVisible(true);
    }//GEN-LAST:event_menu_cadastroProdutoActionPerformed

    private void menu_consultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consultarFornecedorActionPerformed
        // TODO add your handling code here:
        ConsultaFornecedor cf = new ConsultaFornecedor();
        cf.setVisible(true);
    }//GEN-LAST:event_menu_consultarFornecedorActionPerformed

    private void menu_consultarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consultarProdutosActionPerformed
        // TODO add your handling code here:
        ConsultaProduto cp = new ConsultaProduto();
        cp.setVisible(true);
    }//GEN-LAST:event_menu_consultarProdutosActionPerformed

    private void menu_vendasEmitirPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_vendasEmitirPedActionPerformed
        // TODO add your handling code here:
        CadastroCompra cp = new CadastroCompra();
        cp.setVisible(true);
    }//GEN-LAST:event_menu_vendasEmitirPedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_Colsultar;
    private javax.swing.JMenuItem menu_cadastroCliente;
    private javax.swing.JMenuItem menu_cadastroFornecedor;
    private javax.swing.JMenuItem menu_cadastroProduto;
    private javax.swing.JMenuItem menu_cadastroVendedor;
    private javax.swing.JMenu menu_cadastros;
    private javax.swing.JMenuItem menu_consultarCliente;
    private javax.swing.JMenuItem menu_consultarFornecedor;
    private javax.swing.JMenuItem menu_consultarProdutos;
    private javax.swing.JMenuItem menu_consultarVendedor;
    private javax.swing.JMenu menu_vendas;
    private javax.swing.JMenuItem menu_vendasEmitirPed;
    // End of variables declaration//GEN-END:variables

    private void readJTableVendedor(ArrayList<Vendedor> listaVendedor) {
    }
}
